image: gitpod/workspace-mysql
ports:
- port: 8001
  onOpen: open-browser
tasks:
- name: Terminal
  command: >
    clear;
    echo "";
    echo "Cosas que puedes hacer en este terminal:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  init: >
    composer install;
    curl 'https://files.phpmyadmin.net/phpMyAdmin/5.0.1/phpMyAdmin-5.0.1-all-languages.zip' > phpMyAdmin-5.0.1-all-languages.zip ;
    unzip phpMyAdmin-5.0.1-all-languages.zip -d public ;
    mv public/phpMyAdmin-5.0.1-all-languages/ public/phpmyadmin
  command: >
    apachectl start ;
    stty rows 23 ;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log